### DISCUSSION TITLE
Consider adding a `<VisuallyHidden />` component

### DISCUSSION THREAD

**Discussion by rpfaeffle** [SchwarzIT/onyx#756] [Ideas]
## Why?

When creating accessible components and websites there is often a need for additional informations that should only be displayed to users in need of screen-readers. Therefore the text should be visually hidden but still visible to screen-readers.

An example would be links that open in a new tab, this behaviour should be announced by the screen-reader to prevent confusion.

## Usage

Example usage:

```vue
<a href="https://onyx.schwarz" target="_blank">
    Onyx Documentation<VisuallyHidden as="span">, opens in new tab</VisuallyHidden>
</a>
```

## Implementation

The implementation of such a component would be quite straightforward.

```scss
.visually-hidden {
    border: 0;
    clip: rect(0, 0, 0, 0);
    height: 0;
    margin: 0;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
    white-space: nowrap;
}
```

```vue
<script setup lang="ts">
defineProps<{
  as?: string;
}>()
</script>

<component :is="as ?? 'span'"></slot ></component>
```
